services:

  namenode:
    platform: linux/amd64
    build: ./hadoop/namenode
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - ./hadoop/namenode/data:/hadoop/dfs/name
      - ./hadoop/applications:/hadoop/applications
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop/.env

  datanode1:
    platform: linux/amd64
    build: ./hadoop/datanode
    container_name: datanode1
    restart: always
    volumes:
      - ./hadoop/datanode/data/datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9000"
    env_file:
      - ./hadoop/.env

  datanode2:
    platform: linux/amd64
    build: ./hadoop/datanode
    container_name: datanode2
    restart: always
    volumes:
      - ./hadoop/datanode/data/datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9000"
    env_file:
      - ./hadoop/.env

  resourcemanager:
    platform: linux/amd64
    build: ./hadoop/resourcemanager
    container_name: yarn
    ports:
      - "8088:8088"
    restart: always
    depends_on:
      - namenode
      - datanode1
      - datanode2
    environment:
      SERVICE_PRECONDITION: 'namenode:9000 datanode1:9864 datanode2:9864'
    env_file:
      - ./hadoop/.env

  nodemanager:
    platform: linux/amd64
    build: ./hadoop/nodemanager
    container_name: nodemanager
    ports:
      - "8042:8042"
    restart: always
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - resourcemanager
    environment:
      SERVICE_PRECONDITION: 'namenode:9000 datanode1:9864 datanode2:9864 resourcemanager:8088'
    env_file:
      - ./hadoop/.env

  historyserver:
    platform: linux/amd64
    build: ./hadoop/historyserver
    container_name: historyserver
    ports:
      - "8188:8188"
    restart: always
    volumes:
      - ./hadoop/historyserver/data:/hadoop/yarn/timeline
    depends_on:
      - namenode
      - datanode1
      - datanode2
    environment:
      SERVICE_PRECONDITION: 'namenode:9000 datanode1:9864 datanode2:9864'
    env_file:
      - ./hadoop/.env

  python-server:
    build: ./
    container_name: python_server
    ports:
      - "8080:8080"
    environment:
      SERVICE_PRECONDITION: 'namenode:9000 datanode1:9864 datanode2:9864'
    depends_on:
      - namenode
      - datanode1
      - datanode2
